# Generated by Django 4.0.6 on 2022-08-09 15:11

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateField(default=books.models.date_now),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(default=books.models.get_return_date),
        ),
    ]
