# Generated by Django 4.0.5 on 2022-08-19 18:12

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateField(default=books.models.date_now),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(default=books.models.get_return_date),
        ),
        migrations.AlterField(
            model_name='returned_book',
            name='date_of_return',
            field=models.DateTimeField(default=books.models.date_now),
        ),
        migrations.AlterField(
            model_name='returned_book',
            name='return_date',
            field=models.DateField(default=books.models.get_return_date),
        ),
    ]
