# Generated by Django 4.0.5 on 2022-08-23 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_issuedbook_user_alter_issuedbook_issued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedbook',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
