# Generated by Django 4.0.6 on 2022-08-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_issuedbook_issued_date_and_more'),
        ('books', '0003_requestedbook_user'),
    ]

    operations = [
    ]
